package view;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JOptionPane;

import controller.MainController;
import model.Department;
import model.Faculty;

/**
 *
 * @author Capa
 */
public class FacultadesPanel extends javax.swing.JPanel {

    /**
     * Creates new form FacultadesPanel
     */
    public FacultadesPanel(MainController ctrl) {
    	this.controlador = ctrl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButtonSearch = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListFaculty = new javax.swing.JList<Faculty>();
        jTextFieldFaculty = new javax.swing.JTextField();
        jButtonAddFaculty = new javax.swing.JButton();
        jButtonDeleteFaculty = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListDepartments = new javax.swing.JList<Department>();
        jButtonAddDepartment = new javax.swing.JButton();
        jTextFieldDepartmentName = new javax.swing.JTextField();
        jButtonDeleteDepartment = new javax.swing.JButton();

        jButtonSearch.setText("Buscar");

        jTextFieldSearch.setText("Búsqueda...");

        jListFaculty.setModel(controlador.getFacultyModel());
        jListFaculty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jListFacultyFocusGained(evt);
            }
        });
        jListFaculty.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int index = jListFaculty.locationToIndex(e.getPoint());
                    //model.getElementAt(index);
                    controlador.changeDepartmentsModel(index);
                    //TODO BORRAR MODEL ACTUAL
                    jListDepartments.setModel(controlador.getDepartmentsModel());
                    jListFaculty.repaint();
                }
            }
        });
        jScrollPane1.setViewportView(jListFaculty);

        jTextFieldFaculty.setText("Facultad para añadir...");

        jButtonAddFaculty.setText("Añadir facultad");

        jButtonDeleteFaculty.setText("Eliminar Facultad Seleccionada");

        jListDepartments.setModel(controlador.getDepartmentsModel());
        jScrollPane2.setViewportView(jListDepartments);

        jButtonAddDepartment.setText("Añadir Departamento");

        jTextFieldDepartmentName.setText("Departamento para añadir...");

        jButtonDeleteDepartment.setText("Eliminar Departamento Seleccionado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTextFieldSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSearch))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jTextFieldDepartmentName)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAddDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonDeleteDepartment))
                                .addGap(0, 244, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldFaculty)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAddFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDeleteFaculty)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearch)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteDepartment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDeleteFaculty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAddFaculty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldFaculty)))
        );
    }// </editor-fold>                        


    private void jListFacultyFocusGained(java.awt.event.FocusEvent evt) {
    	System.out.println(evt.getSource());
    	System.out.println(evt.getComponent());
    	System.out.println(evt.toString());
    	System.out.println(evt.getClass());
        jListDepartments.setModel(controlador.getDepartmentsModel());
    } 
    // Variables declaration - do not modify                     
    private MainController controlador;
    private javax.swing.JButton jButtonAddFaculty;
    private javax.swing.JButton jButtonDeleteDepartment;
    private javax.swing.JButton jButtonDeleteFaculty;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JList<Department> jListDepartments;
    private javax.swing.JList<Faculty> jListFaculty;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jButtonAddDepartment;
    private javax.swing.JTextField jTextFieldDepartmentName;
    private javax.swing.JTextField jTextFieldFaculty;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration                   
}
